// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4rZ6CyFQS9VByOFJWhh0qsxvZgupanuw',
    appId: '1:135596724209:web:114d608b98738a4c267e50',
    messagingSenderId: '135596724209',
    projectId: 'social-crossplatform',
    authDomain: 'social-crossplatform.firebaseapp.com',
    storageBucket: 'social-crossplatform.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD11T3uFY8g5FBaPjrcopj-X-7hpmwZ-0Y',
    appId: '1:135596724209:android:a0c10165f7f33de1267e50',
    messagingSenderId: '135596724209',
    projectId: 'social-crossplatform',
    storageBucket: 'social-crossplatform.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYbpW0OkjoBLw0ff8OGSEmov50D_YWTf8',
    appId: '1:135596724209:ios:96053df46b201e2a267e50',
    messagingSenderId: '135596724209',
    projectId: 'social-crossplatform',
    storageBucket: 'social-crossplatform.appspot.com',
    iosClientId: '135596724209-2pbntooj76adbfklt6ciec7maqlopd8i.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialCrossplatform',
  );
}
